def GetVoiceLines():
    return [
"Children, Behave (Ana)",
"Everyone Dies (Ana)",
"Go On... I Can Wait (Ana)",
"It Takes A Woman To Know (Ana)",
"Justice Rains From Above (Ana)",
"Mother Knows Best (Ana)",
"No Scope Needed (Ana)",
"Someone To Tuck You In? (Ana)",
"What Are You Thinking? (Ana)",
"Witness Me (Ana)",
"You Know Nothing (Ana)",
"Burn It All Down (Ashe)",
"How Do You Even Live? (Ashe)",
"I'm A Rebel (Ashe)",
"I Run This Show (Ashe)",
"Just Taking Out The Trash (Ashe)",
"Life's Little Pleasures (Ashe)",
"Need Me To Repeat Myself? (Ashe)",
"That's Rich (Ashe)",
"This Is A Stick Up (Ashe)",
"Try And Keep It Together (Ashe)",
"Watch Your Language (Ashe)",
"An Apple A Day (Baptiste)",
"Appreciation (Baptiste)",
"Buy You A Drink (Baptiste)",
"Damn (Baptiste)",
"Expert Opinion (Baptiste)",
"Going To Sting (Baptiste)",
"Settle Down (Baptiste)",
"Survival Tip (Baptiste)",
"Some Kind Of Angel (Baptiste)",
"Time's Up, Pencils Down (Baptiste)",
"What Are You Trying To Pull (Baptiste)",
"Beeple (Bastion)",
"Boo Boo Doo De Doo (Bastion)",
"Bweeeeeeeeeee (Bastion)",
"Chirr Chirr Chirr (Bastion)",
"Dah-Dah Weeeee! (Bastion)",
"Dun Dun Boop Boop (Bastion)",
"Dweet Dweet Dweet! (Bastion)",
"Hee Hoo Hoo (Bastion)",
"Ooh-Ooo-Hoo-Hoo (Bastion)",
"Sh-Sh-Sh (Bastion)",
"Zwee? (Bastion)",
"Be Reasonable (Brigitte)",
"Get Lost (Brigitte)",
"It's Broken (Brigitte)",
"Leave This To The Experts (Brigitte)",
"Mace To The Face (Brigitte)",
"No Shortcuts (Brigitte)",
"Swedish Engineering (Brigitte)",
"Trust Me (Brigitte)",
"What Are You Doing (Brigitte)",
"Working As Intended (Brigitte)",
";) (D.Va)",
"A New Challenger! (D.Va)",
"AFK (D.Va)",
"Aw, Yeah! (D.Va)",
"D.Va: 1, Bad Guys: 0 (D.Va)",
"GG! (D.Va)",
"I Play to Win (D.Va)",
"Is This Easy Mode? (D.Va)",
"LOL (D.Va)",
"Nice Try (D.Va)",
"No Hacks Required (D.Va)",
"Combo Breaker (Doomfist)",
"Don't Get Back Up (Doomfist)",
"Go And Sit Down (Doomfist)",
"I Haven't Even Started (Doomfist)",
"K.O. (Doomfist)",
"One Punch Is All I Need (Doomfist)",
"Spare Me the Commentary (Doomfist)",
"Talk To The Fist (Doomfist)",
"You're Not Bad (Doomfist)",
"You Must Be Joking (Doomfist)",
"You Test My Patience (Doomfist)",
"Come On! (Genji)",
"Damn! (Genji)","Death Is Whimsical Today (Zenyatta)",
"Do I Think? (Zenyatta)",
"Free Your Mind (Zenyatta)",
"Hello, World! (Zenyatta)",
"How Amusing (Zenyatta)",
"I Dreamt I Was A Butterfly (Zenyatta)",
"I Think, Therefore I Am (Zenyatta)",
"I Will Not Juggle (Zenyatta)",
"Ones And Zeroes (Zenyatta)",
"Peace And Blessings (Zenyatta)",
"The Iris Embraces You (Zenyatta)","Are You Scared? (Ana)",
"Don't be Scared! (Ana)",
"W-W-Wooooo...? (Bastion) (an anxious questioning sound)",
"Oooooooooooo… (Bastion) (A frighten shivering voice)",
"Not Scared, Are You (Brigitte) ('You're not scared, are you?')",
"Supposed To Scare Me (Brigitte) ('Was that supposed to scare me?')",
"Happy Halloween! (D.Va)",
"I'm Not Scared. (D.Va)",
"I Have Something For You (Doomfist) ('I have something right here for you.')",
"You Should Be Scared (Doomfist)",
"Happy Halloween(Genji) ('良いハロウィンを')",
"My Halloween Costume? (Genji) ('My Halloween costume?... Cyborg ninja.')",
"Trick Or Treat (Genji)",
"You Are Already Dead (Hanzo)",
"Master Your Fears (Hanzo) ('Master your fears...lest they master you.')",
"Happy Halloween (Junkrat)",
"I'm Alive! (Junkrat) ('I'm aliiivvee…euh!')",
"Killed It! (Lúcio)",
"So Good It's Scary! (Lúcio)",
"Trick Or Treat (Lúcio)",
"It's Your Funeral (McCree) ('Heh... It's your funeral!')",
"I Hear You, Pumpkin (McCree)",
"Trick Or Treat (McCree)",
"Scary! (Mei)",
"Did You Hear Something? (Mei)",
"Superstition (Mercy) ('Pheh... superstition.')",
"Sometimes You Scare Me (Mercy)",
"Despair Has Its Own Calms (Moira)",
"Happy Halloween (Moira) ('Oíche shamhna shona duit')",
"Be Careful (Orisa) ('Be careful when crossing the street.')",
"Your Pulse Has Increased (Orisa) ('Your pulse has increased. Are you frightened?')",
"Are You Frightened? (Pharah)",
"Dead Or Alive (Pharah) ('You're going to come with me, dead or alive!')",
"I'm So Scared (Pharah)",
"I'm Dressed To Kill (Reaper)",
"I Work The Graveyard Shift (Reaper)",
"Things Are Looking Grim (Reaper) ('Things are looking...grim.')",
"Smashing (Reinhardt)",
"What Do We Have Here? (Reinhardt)",
"Boo! (Roadhog)",
"Want Some Candy? (Roadhog)",
"Knock Knock (Soldier: 76)",
"Trick Or Treat (Soldier: 76)",
"Aw, Isn't That Sweet? (Sombra)",
"You Trying To Be Scary? (Sombra)",
"A Frightening Thought (Symmetra) ('What a frightening thought.')",
"The Treat Is A Lie (Symmetra)",
"If You Build It (Torbjörn) ('Ohohohoo... if you build it, they will die.')",
"I Smell Trouble Brewing (Torbjörn)",
"Ooh, Scary! (Tracer)",
"Boo! (Tracer)",
"Trick Or Treat (Tracer)",
"Morning Spider…(Widowmaker) ('Araignée du matin, chagrin. Araignée du soir, cauchemar.')",
"The Party Is Over (Widowmaker)",    
"Boo! (Winston)",
"This Is Not A Costume (Winston)",
"Ooh, Scary (Winston)",
"Heart Rate Increasing (Wrecking Ball)",
"Trick Or Treat (Wrecking Ball)",
"Don't Be Scared (Zarya)",
"Never Forget The Fallen (Zarya)",
"Trick Or Treat? (Zenyatta)",
"Frightening (Zenyatta)",
"I'm Too Old For Surprises (Ana)",
"I'm Watching Out For You (Ana)",
"Girl Who Has Everything (Ashe)",
"It's A Giving Time Of Year (Ashe)",
"Bwoo Bwoo Bwoo (Bastion)",
"Dwee Doo Hoo (Bastion)",
"I Made That Just For You (Brigitte)",
"Merry Christmas (Brigitte)",
"Aw, You Shouldn't Have (D.Va)",
"Happy Holidays (D.Va)",
"Did You Bring Me A Present? (Doomfist)",
"They Say Chivalry Is Dead (Doomfist)",
"Count Your Blessings (Genji)",
"Merry Christmas! (Genji)",
"A Gift For You (Hanzo)",
"Cold As Ice (Hanzo)",
"Out Cold (Hanzo)",
"Go On... Give It A Shake! (Junkrat)",
"Happy Holidays (Junkrat)",
"Merry Christmas (Junkrat)",
"Climbing The Charts! (Lúcio)",
"Happy Holidays! (Lúcio)",
"Had To Break The Ice (McCree)",
"You've Been Snowed In (McCree)",
"Don't You Love Surprises (Mei)",
"I Got You Something! (Mei)",
"Snowball Fight! (Mei)",
"I Could Use The Time Off (Mercy)",
"Your Guardian Angel (Mercy)",
"Absolute Zero (Moira)",
"Happy Christmas (Moira)",
"The Gift Of Knowledge (Moira)",
"Annual Performance Analysis (Orisa)",
"Can't I Guide Your Way Tonight (Orisa)",
"At Ease (Pharah)",
"Cool It (Pharah)",
"The Forecast (Pharah)",
"Holiday Spirit (Reaper)",
"You're On Ice (Reaper)",
"Forgive And Forget (Reinhardt)",
"You're On My Naughty List (Reinhardt)",
"Ho Ho Ho (Roadhog)",
"I Have Your Present Right Here (Roadhog)",
"Merry Christmas (Soldier: 76)",
"Stay Frosty (Soldier: 76)",
"I Can Be Nice (Sombra)",
"I Know Who's Been Naughty (Sombra)",
"Merry Christmas (Sombra)",
"Expecting A Miracle? (Symmetra)",
"I Made You Something (Symmetra)",
"Expert Craftsmanship (Torbjörn)",
"Made To Order (Torbjörn)",
"Ho Ho Ho! (Tracer)",
"It's In The Bag (Tracer)",
"Exquisite (Widowmaker)",
"Happy Holidays (Widowmaker)",
"Merry Christmas (Widowmaker)",
"I... Got You Something (Winston)",
"Party Mode Engaged (Winston)",
"Deck The Halls (Wrecking Ball)",
"Ho. Ho. Ho. (Wrecking Ball)",
"Cool It (Zarya)",
"For The Motherland (Zarya)",
"Is It Cold In Here? (Zarya)",
"Joy To The World (Zenyatta)",
"No Snowflake (Zenyatta)",
"Snowball Fight? (Zenyatta)",    "I Make My Own Luck (Ana)",
"The Moon In Winter (Ana)",
"No One Likes A Squealer (Ashe)",
"Ready For The Fireworks (Ashe)",
"Doo Wee Doo Wee (Bastion)",
"Woop Doo Woo Dun Woop (Bastion)",
"All That Glitters (Brigitte)",
"Who's Ready To Party (Brigitte)",
"Happy New Year (D.Va)",
"The Best Things In Life (D.Va)",
"Fortune Favors The Bold (Doomfist)",
"I'll Throw You A Bone (Doomfist)",
"All Bark, No Bite (Genji)",
"To Know Yourself (Genji)",
"Insolent Cur (Hanzo)",
"Pointless Frivolity (Hanzo)",
"When The Moon Is Full (Hanzo)",
"Gong Xi Fa Cai (Junkrat)",
"Happy New Year (Junkrat)",
"My Dog Is Barking (Junkrat)",
"I Make This Look Good... (Lúcio)",
"Just How I Like It (Lúcio)",
"Calls For A Celebration (McCree)",
"Hair Of The Dog (McCree)",
"How's That For Fireworks (McCree)",
"Give Me A Red Envelope (Mei)",
"Wishing You Prosperity (Mei)",
"A Most Impressive Display (Mercy)",
"How Lucky For You (Mercy)",
"Slánte (Moira)",
"You've Made A Dogs Breakfast (Moira)",
"The Moon That Wanes (Orisa)",
"Who Is Ready To Party (Orisa)",
"I Keep The Peace (Pharah)",
"Ready For Some Fireworks (Pharah)",
"I Have The Devil's Own Luck (Reaper)",
"Now Those Are Fireworks (Reaper)",
"Are You Chicken? (Reinhardt)",
"Fortune Favors The Bold (Reinhardt)",
"It's All Gone To The Dogs (Roadhog)",
"You Chicken? (Roadhog)",
"Respect Your Elders (Soldier: 76)",
"The Rooster Crows (Soldier: 76)",
"You're Easily Impressed (Sombra)",
"You're In The Doghouse (Sombra)",
"Cause For Celebration (Symmetra)",
"Good Fortune (Symmetra)",
"Everyone Get In Here (Torbjörn)",
"Too Hot For You? (Torbjörn)",
"I'm Over The Moon (Tracer)",
"Ready For Some Fireworks? (Tracer)",
"Barking Up The Wrong Tree (Widowmaker)",
"You Have My Attention (Widowmaker)",
"Moon Sweet Home (Winston)",
"To The Moon And Back (Winston)",
"That Was Awesome! (Winston)",
"Get Pumped (Zarya)",
"Where The Dog Is Buried (Zarya)",
"Every Rooster Crows (Zenyatta)",
"Fortune Favors Me (Zenyatta)",    "Damn (Ana)",
"The Ghost Watches (Ana)",
"We're Not Keeping Score (Ana)",
"Do You Trust Me (Ashe)",
"Fetch My Butler (Ashe)",
"Mind Your Manners (Ashe)",
"Associates (Baptiste)",
"Caribbean Coalition (Baptiste)",
"Lieutenant Augustin (Baptiste)",
"Dwee Wee Woh (Bastion)",
"Zwee-ah Wheee Doo Woo (Bastion)",
"Zwing Zwing Zwing (Bastion)",
"Don't Get Caught (Brigitte)",
"A Chicken Out Of A Feather (Brigitte)",
"If You Make Your Bed, Lie In It (Brigitte)",
"Time To Roll Up My Sleeves (Brigitte)",
"Amazing (D.Va)",
"Not Taking Me Seriously (D.Va)",
"Try And Keep Up (D.Va)",
"I Am Not Your Savior (Doomfist)",
"I Didn't Ask For Your Opinion (Doomfist)",
"I Know You Can Do Better (Doomfist)",
"Another! (Genji)",
"Life And Death Balance (Genji)",
"Your Eyes Deceive You (Genji)",
"Beauty In Simplicity (Hanzo)",
"History Forged By The Sword (Hanzo)",
"My Fate Is Written In Blood (Hanzo)",
"Unacceptable (Hanzo)",
"Come The Raw Prawn (Junkrat)",
"I Really Blew That One (Junkrat)",
"Too Right! (Junkrat)",
"Boop (Lúcio)",
"Learn To Take It Easy (Lúcio)",
"Turn It Up In My Headphones (Lúcio)",
"A Man's Gotta Have Rules (McCree)",
"Don't Sass Me (McCree)",
"Gathering No Moss (McCree)",
"The Old Fashioned Way (McCree)",
"A New Adventure (Mei)",
"I'm Just A Scientist (Mei)",
"Science This (Mei)",
"Scientific Explanation (Mei)",
"A Timely Intervention (Mercy)",
"I'm Needed Somewhere (Mercy)",
"Not Sure Why I Bother (Mercy)",
"Take Care Of Yourself (Mercy)",
"Faith In Science (Moira)",
"Get Off The Stage (Moira)",
"This Is To My Liking (Moira)",
"You're Mistaken (Moira)",
"Error: Division By 0 (Orisa)",
"Functionality Still In Beta (Orisa)",
"Don't Take It Personally (Pharah)",
"From My Mother (Pharah)",
"I Am The Rocket Queen (Pharah)",
"I Live For A Good Fight (Pharah)",
"Amateur Hour(Reaper)",
"Moving On (Reaper)",
"Revenge Is Sweet (Reaper)",
"Easy Does It (Reinhardt)",
"Prost (Reinhardt)",
"Unstopppable (Reinhardt)",
"Killed For Less Than That (Roadhog)",
"She'll Be Right (Roadhog)",
"You Wanna Scrap With Me? (Roadhog)",
"Don't Call Me A Hero (Soldier: 76)",    "Follow Me (Ana)",
"The Adults Are Talking (Ana)",
"You Need To Learn To Relax (Ana)",
"Bew-Woo Bew-Woo (Bastion)",
"Doo Dun Dun Woo (Bastion)",
"Zur Zur Ee Num (Bastion)",
"It's Just A Flesh Wound (Brigitte)",
"Leave This To An Expert (Brigitte)",
"No Problem (Brigitte)",
"Level Up! (D.Va)",
"No Way (D.Va)",
"Take It On The Chin (Doomfist)",
"You Can't Win(Doomfist)",
"Your Lack Of Belief (Doomfist)",
"I'm Not Impressed (Genji)",
"You Need Healing (Genji)",
"You Seem Nice (Genji)",
"An Error In Judgement (Hanzo)",
"Do Not Rouse The Dragon (Hanzo)",
"Just So (Hanzo)",
"Dipstick (Junkrat)",
"Inconspicuous (Junkrat)",
"Oops... Dropped Something (Junkrat)",
"Can You Hear Me Now? (Lúcio)",
"Everyone Gets Their +1 (Lúcio)",
"Have Some Lúcio-Oh's! (Lúcio)",
"Buckle Up (McCree)",
"How Do You Like Me Now? (McCree)",
"Next Round's On Me (McCree)",
"I Was Only Trying To Help (Mei)",
"So Mean! Honestly... (Mei)",
"Wake Up, Sleepyhead! (Mei)",
"I've Seen Worse (Mercy)",
"Questionable Judgement (Mercy)",
"You're Welcome (Mercy)",
"Good News, Everyone (Moira)",
"This Was A Triumph (Moira)",
"Unbelievable (Moira)",
"I Have A Bad Feeling About This (Orisa)",
"Satisfied With Protection (Orisa)",
"Your Compliance (Orisa)",
"Fly Casual (Pharah)",
"Try Me (Pharah)",
"Stay On Target (Pharah)",
"I'll See You In Hell (Reaper)",
"No One Left Behind (Reaper)",
"Pathetic (Reaper)",
"Beer! (Reinhardt)",
"Come Here... (Reinhardt)",
"Honor! Justice! Reinhardt! (Reinhardt)",
"I'm Going Hog Wild! (Roadhog)",
"I Don't Like Talkers (Roadhog)",
"That's My Business (Roadhog)",
"I'm Not Your Father (Soldier: 76)",
"Want Something Done Right? (Soldier: 76)",
"You're The Boss (Soldier: 76)",
"I Need A Drink (Sombra)",
"Let's Not Do That Again (Sombra)",
"Were You Done Talking? (Sombra)",
"Let Us Discuss Your Failures (Symmetra)",
"Setting Up The Car Wash (Symmetra)",
"Your Mind Works (Symmetra)",
"Hear Me, Baby? (Torbjörn)",
"Trust Me (Torbjörn)",
"Why Didn't I Think Of That? (Torbjörn)",
"Did I Miss Something? (Tracer)",
    "I Knew I Forgot Something (Tracer)",
"Too Slow! (Tracer)",
"Sorry (Widowmaker)",
"What A Bore (Widowmaker)",
"The Pleasure Is Mine (Widowmaker)",
"Can't Keep A Good Ape Down (Winston)",
"It's My Time To Shine! (Winston)",
"Oh Yeah! (Winston)",
"Is That All? (Zarya)",
"Let's Get Physical (Zarya)",
"Peace Through Firepower (Zarya)",
"Existence Is Mysterious (Zenyatta)",
"How Disappointing (Zenyatta)",
"Patience (Zenyatta)"
    ]