# Commands/ChatCommands/chat_cog.py
import discord
from discord.ext import commands
from discord import app_commands
from GPT_stories import getStoryByRole
from utils.gpt import generate_gpt_response
from utils.message_utils import send_message_in_chunks
from config.config import SERVERS

class ChatCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="askbread", description="Responds with a custom message generated by OpenAI, incorporating humor related to banana bread.")
    @app_commands.guilds(*SERVERS)
    async def askbread(self, interaction: discord.Interaction, user_input: str, role: str):
        await interaction.response.defer()
        story = getStoryByRole(role, interaction.user.id)
        model = "gpt-4o"
        response_message = await generate_gpt_response(model, story, user_input)
        await send_message_in_chunks(response_message, interaction)

async def setup(bot):
    await bot.add_cog(ChatCog(bot))
