
from GPT_stories import getStoryByRole
import discord
from discord.ext import commands
from discord import app_commands
async def define_ask_bread_command(tree, servers, client):
    @tree.command(name="askbread", description="Responds with a custom message generated by OpenAI, incorporating humor related to banana bread.", guilds=servers)
    async def askbread(interaction: discord.Interaction, user_input: str, role: str):
        await interaction.response.defer()

        story = getStoryByRole(role, interaction.user.id)
        if interaction.user.id == 212635381391294464:
            model = "gpt-4-turbo"
        else:
            model = "gpt-3.5-turbo"
        # Generate the completion response using the selected story
        completion_response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": story},
                {"role": "user", "content": user_input}
            ]
        )
        response_message = completion_response.choices[0].message.content[:1999]
        await interaction.followup.send(response_message)